language: python
cache: pip
python:
  - 3.7
  - 3.8
  - 3.9

before_install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install --upgrade pipenv

install:
  - pipenv install --dev

script:
  - pipenv run pytest --cov=algobot

after_success:
  - bash <(curl -s https://codecov.io/bash)
