name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pre-commit
            ~/.cache/pip
          key: pip-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements-dev.txt') }}-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pre-commit mypy
          python -m pip install -r requirements-dev.txt
      - name: Run tests
        run: pytest
      - name: Run pre-commit
        run: pre-commit run --verbose --all-files --show-diff-on-failure
      # FIXME: mypy is failing due to missing types-* packages
      # - name: Run mypy
      #   run: mypy algorithms_keeper/ tests/
      - name: Upload coverage to Codecov
        if: ${{ success() }}
        run: bash <(curl -s https://codecov.io/bash)
